name: CI Pipeline

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: cations/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests and capture logs
        run: |
          pytest > failure.log || true

      - name: Upload failure log
        uses: actions/upload-artifact@v6
        with:
          name: failure-log
          path: failure.log
